### ISSUE TITLE
Particles leaving top left bounds

### ISSUE THREAD

**Issue by stonapse64** [vmdharan/ParticlesApp#1]
Hi vmdharan, I saw that the particles are leaving the top left bounds a bit before bouncing into their new directions. 

Here a slightly modified version of the canvasWin2d_Update method:

        private void canvasWin2d_Update(ICanvasAnimatedControl sender, CanvasAnimatedUpdateEventArgs args)
        {
            // Loop over all the particles.
            for (int i = 0; i < maxParticles; i++)
            {
                // Update the horizontal position.
                particles[i].newLeft += particles[i].hDir;

                // If outside the bounds, then invert the direction of motion.
                // if (particles[i].newLeft <= 0)
                if (particles[i].newLeft - radius <= 0)
                {
                    particles[i].hDir = 1;
                }
                else if (particles[i].newLeft >= wComponent)
                {
                    particles[i].hDir = -1;
                }

                // Update the vertical position.
                particles[i].newTop += particles[i].vDir;

                // If outside the bounds, then invert the direction of motion.
                // if (particles[i].newTop <= 0)
                if (particles[i].newTop - radius <= 0)
                {
                    particles[i].vDir = 1;
                }
                else if (particles[i].newTop >= hComponent)
                {
                    particles[i].vDir = -1;
                }
            }
        }

Nice blog post! It really helped me understand to use this control. Thanks.

**Comment by vmdharan** [comment]
Hi stonapse64,

Thanks for the feedback. Much appreciated.

I have just applied your recommended fixes to the code and pushed it to the repository.

Will also update the blog post so that these bugs are fixed there too. Hope that is okay with you.

**Comment by stonapse64** [comment]
Hi VJ, Thank you for the update.
