### ISSUE TITLE
Particles initial directions are all equal / similar

### ISSUE THREAD

**Issue by stonapse64** [vmdharan/ParticlesApp#2]
Hi vmdharan,
I noticed that all particles are moving into similar directions. Here's a suggestions to give each particle an individual random start vector2 in canvasWin2d_CreateResources:

            // Loop over all the particles and draw them on the canvas.
            for (int i = 0; i < maxParticles; i++)
            {
                particles[i].newLeft = rand.Next(0, wComponent);
                particles[i].newTop = rand.Next(0, hComponent);
                particles[i].col1 = scb[rand.Next(0, 9)];

                //particles[i].hDir = rand.Next(1, 2) * -1;
                //particles[i].vDir = rand.Next(1, 2) * -1;

                particles[i].hDir = rand.Next(0, 2) == 0 ? -1 : 1;
                particles[i].vDir = rand.Next(0, 2) == 0 ? -1 : 1;
            }

Thanks again for your blog post.

**Comment by vmdharan** [comment]
Hi stonapse64,

That's a great suggestion. 

I just implemented it on my machine and it looks much better.

Thanks for the feedback. I really appreciate it.

Cheers,
VJ

**Comment by stonapse64** [comment]
Hi VJ, I'm delighted that you liked it. :-) I'm thinking of adding collision detection and some sort of game of life effect fitting to our global situation. Will be my early summer coding challenge. Gonna keep you in the loop if you like. Cheers!

**Comment by vmdharan** [comment]
Hey Andreas, 

Sure, let me know how it goes. I'm also trying to build a particle effects system for my game engine, so I'd be eager to hear about your experiences with UWP.

Cheers,
VJ
